INITIALIZING:
	db "CTRL-TAB OS INITIALIZING",0
LOADING_KERNEL:
  db "LOADING KERNEL",0
KERNEL_LOADED:
	db "KERNEL LOADED SUCCESFULLY",0
SWITCHING:
	db "SWITCHING TO PROTECTED MODE",0
SWITCHED:
	db "SWITCHED TO 32-bit PROTECTED MODE",0
DISK_ERROR_MSG:
  db "ERROR LOADING KERNEL",0
